project:
  type: book

book:
  title: "Digital Lab Notebook"
  author: "Kelly Purdy"
  chapters:
    - index.qmd
    - chapter-01.qmd
    - chapter-02.qmd
    - chapter-03.qmd
    - chapter-04.qmd
    - chapter-05.qmd

format:
  html:
    theme: cosmo
    toc: true
    